name: Take screenshots

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "50 0,2,4,6,10,14,16,18,20,22 * * *"

permissions:
  contents: write

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - uses: actions/github-script@v7
      name: Create shots.yml if missing on first run
      with:
        script: |
          const fs = require('fs');
          if (!fs.existsSync('shots.yml')) {
              const desc = context.payload.repository.description;
              let line = '';
              if (desc && (desc.startsWith('http://') || desc.startsWith('https://'))) {
                  line = `- url: ${desc}` + '\n  output: shot.png\n  height: 800';
              } else {
                  line = '# - url: https://www.example.com/\n#   output: shot.png\n#   height: 800';
              }
              fs.writeFileSync('shots.yml', line + '\n');
          }
    - name: Take shots
      run: |
        shot-scraper multi shots.yml --har-file trace.zip
    - name: Save HTML
      run: |
        chmod +x shot_scraper_html.sh
        ./shot_scraper_html.sh
        
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
    - name: Upload HAR
      uses: actions/upload-artifact@v4
      with:
        name: trace.zip
        path: trace.zip

    - name: Generate Image Diffs
      run: | 
        git status -s --untracked-files=no --porcelain | sed "s/^ M //" | grep ".png" | xargs python3 image_diff.py
    - name: Upload Image Diffs
      uses: actions/upload-artifact@v4
      with:
        name: image_diffs
        path: |
          diffs/**.png
